server:
  servlet:
    context-path: /spring-boot-testing
  port: 9090
spring:
  application:
    name: spring boot testing
  data:
    mongodb:
      uri: mongodb://${SPRING_DATASOURCE_HOST_NAME}:${SPRING_DATASOURCE_PORT}/${SPRING_DATASOURCE_DATABASE_NAME}
# //      uri: mongodb://localhost:27017/product-service      