name: Frc Project Pipeline
on: push
jobs:
  compileAndbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Java and Maven
        uses: actions/setup-java@v4  
        with:
         java-version: '17'
         distribution: 'adopt'
      - name: Compile 
        run: mvn compile 
      - name: Install dependencies and Build 
        run: mvn clean install
  test:  
    needs: compileAndbuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Java and Maven
        uses: actions/setup-java@v4  
        with:
         java-version: '17'
         distribution: 'adopt'
      - name: Test 
        run: mvn test  
  deploy:
    needs: [compileAndbuild]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Java and Maven
        uses: actions/setup-java@v4  
        with:
         java-version: '17'
         distribution: 'adopt'
      - name: Package
        run: mvn clean package -DskipTests  
      - name: Deploy
        run: echo "Deployee"  

        