name: Frc Project Pipeline
on: 
 push: 
    branches:
        - main
env: 
  SPRING_DATASOURCE_HOST_NAME: localhost   
  SPRING_DATASOURCE_PORT: 27017
  SPRING_DATASOURCE_DATABASE_NAME: product-service       
jobs:
  compileAndbuild:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Java and Maven
        uses: actions/setup-java@v4  
        with:
         java-version: '17'
         distribution: 'adopt'
      - name: Cache dependencies
        uses: actions/cache@v4 
        with: 
         path: ~/.m2/repository  
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
              ${{ runner.os }}-maven-      
      - name: Compile 
        run: mvn compile 
      - name: Install dependencies and Build 
        run: mvn clean install -DskipTests  
      - name: Output env Information
        run: echo "SPRING_DATASOURCE_DATABASE_NAME -  ${{ env.SPRING_DATASOURCE_DATABASE_NAME }}"  
  test:  
    needs: compileAndbuild
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Java and Maven 
        uses: actions/setup-java@v4  
        with:
         java-version: '17'
         distribution: 'adopt'
      - name: Cache dependencies
        uses: actions/cache@v4 
        with: 
         path: ~/.m2/repository  
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
              ${{ runner.os }}-maven-          
      - name: Test 
        run: mvn clean test -fn surefire-report:report  -Daggregate=true
      - name: Output Test contents 
        run: |
         cd target/surefire-reports
         ls 
  build:
    needs: test
    runs-on: ubuntu-latest
    outputs:
        jar-file: ${{ steps.publish-jar.outputs.jar-file }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Java and Maven
        uses: actions/setup-java@v4  
        with:
         java-version: '17'
         distribution: 'adopt'
      - name: Cache dependencies
        uses: actions/cache@v4 
        with: 
         path: ~/.m2/repository  
         key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
         restore-keys: |
              ${{ runner.os }}-maven-          
      - name: Package
        run: mvn clean package -DskipTests  
      - name: Output contents 
        run: |
          cd target
          ls        
      - name:  Publish jar filename
        id:    publish-jar
        run : find target/*.jar -type f -execdir echo 'jar-file={}' >> $GITHUB_OUTPUT ';'
      - name:  Upload artifacts
        uses: actions/upload-artifact@v4
        with:
            name: artifacts
            path: target/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Java and Maven
        uses: actions/setup-java@v4  
        with:
         java-version: '17'
         distribution: 'adopt'
      - name:  Get build artifacts
        uses: actions/download-artifact@v4
        with:
         name: artifacts
      - name: Output contents 
        run: |
          ls
      - name:  Output filename
        run: echo "${{ needs.build.outputs.jar-file }}"  
      - name: Deploy
        run: echo "Deployee"        

        