name: Reusable Deploy
on: 
  workflow_call:
    inputs: 
      artifacts-name: 
        description: Then name of the deployable artifacts files
        required: false
        default: artifacts-files
        type: string
    secrets:  
      database-name:
        required: true
    outputs:
      result: 
        description: Then name of the deployable artifacts files
        value: "${{ jobs.deploy.outputs.result-out }}"    
         
jobs:    
  deploy:
    runs-on: ubuntu-latest
    outputs:
      result-out: ${{ steps.result-output.outputs.step-result }}
    steps:
     - name: Dwonload artifacts 
       uses: actions/download-artifact@v4
       with:
         name: ${{ inputs.artifacts-name   }}
     - name: List files
       run: ls    
     - name: Output Information
       run: echo "Deploying & uploading..."
     - name: Set result output
       id: result-output
       run: echo "step-result=success" >> $GUTHUB_OUTPUT
